# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "prepare"
  - "jira"
  - "argo-sync"
  - "argo-rollout"
  - "build"
  - "push"
  - "test"
  - "sync"
  
steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: 'nightmar39/test_repo'
    revision: "master"
    git: "github"
    stage: "clone"
  test:
    title: "Running test"
    type: "freestyle" # Run any command
    image: 'ubuntu:latest' # The image in which command will be executed
    working_directory: "${{clone}}" # Running command where code cloned
    shell: bash
    commands:      
      - pwd